// GENERATED by scripts/process-gallery.sh. Do not edit by hand.
// Re-run the script after adding or removing photos.

export type GalleryPhoto = { slug: string; heads: number };

export const GALLERY: GalleryPhoto[] = [
  { slug: "indoor-selfie", heads: 2 },
  { slug: "nour-jamil", heads: 2 },
  { slug: "sally", heads: 1 },
  { slug: "kassem-dia", heads: 2 },
  { slug: "mohammad", heads: 1 },
  { slug: "restaurant-mirror", heads: 2 },
];
