#!/bin/bash
# Turn every photo in assets/photos/incoming/ into web assets, with no
# per-photo configuration: faces are detected, not hardcoded.
#
#   1. drop photos (jpg / png / heic) into assets/photos/incoming/
#   2. ./scripts/process-gallery.sh
#
# For each photo it writes:
#   public/photos/gallery/<slug>-polaroid.webp   square crop framed on the faces
#   public/photos/gallery/<slug>-head-<n>.webp   one die-cut head per face
# and regenerates src/lib/gallery.ts listing them.
#
# Requires ImageMagick (with HEIC), cwebp, and Swift (macOS, for Vision).
set -euo pipefail
cd "$(dirname "$0")/.."
SRC="$PWD/assets/photos/incoming"
OUT="$PWD/public/photos/gallery"
T=$(mktemp -d); trap 'rm -rf "$T"' EXIT
mkdir -p "$OUT"
rm -f "$OUT"/*.webp

echo "==> building Vision helpers"
swiftc -O scripts/lift.swift  -o "$T/lift"
swiftc -O scripts/faces.swift -o "$T/faces"

shopt -s nullglob nocaseglob
photos=("$SRC"/*.jpg "$SRC"/*.jpeg "$SRC"/*.png "$SRC"/*.heic)
shopt -u nocaseglob
if [ ${#photos[@]} -eq 0 ]; then
  echo "No photos in $SRC. Drop some in and re-run." >&2
  exit 1
fi

manifest="$T/manifest.txt"
: > "$manifest"

for photo in "${photos[@]}"; do
  base=$(basename "$photo"); base=${base%.*}
  # Slug: lowercase, non-alphanumerics collapsed to a dash.
  slug=$(printf '%s' "$base" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]\+/-/g; s/^-//; s/-$//')
  echo "==> $base -> $slug"

  # Normalise once: EXIF-oriented sRGB PNG that everything else works from.
  magick "$photo" -auto-orient -colorspace sRGB "$T/$slug-src.png"

  read -r _ iw ih _ nfaces <<<"$("$T/faces" "$photo" | head -1)"
  echo "    ${iw}x${ih}, $nfaces face(s)"

  # ---- polaroid: square crop centred on the faces ----
  read -r cx cy <<<"$("$T/faces" "$photo" | awk '
    /^face/ { n++; cx += $2 + $4/2; cy += $3 + $5/2 }
    END { if (n) printf "%d %d", cx/n, cy/n; else printf "-1 -1" }')"
  side=$(python3 -c "print(min($iw,$ih))")
  read -r px py <<<"$(python3 -c "
iw,ih,side,cx,cy = $iw,$ih,$side,$cx,$cy
if cx < 0: cx, cy = iw//2, ih//2
# Frame on the faces, then clamp so the crop stays inside the image.
x = min(max(int(cx - side/2), 0), iw - side)
y = min(max(int(cy - side*0.42), 0), ih - side)
print(x, y)")"
  magick "$T/$slug-src.png" -crop "${side}x${side}+${px}+${py}" +repage \
    -resize 640x -strip "$T/$slug-pola.png"
  cwebp -quiet -q 80 "$T/$slug-pola.png" -o "$OUT/$slug-polaroid.webp"

  # ---- head stickers: one per detected face ----
  "$T/lift" "$photo" "$T/$slug-matte.png" >/dev/null 2>&1 || {
    echo "    no subject matte, skipping heads"; echo "$slug|0" >> "$manifest"; continue; }

  # Drop passers-by, so a stranger in a restaurant never becomes a sticker on
  # a published page. Measured against the LARGEST face in the same photo, not
  # against the frame: a subject standing further back is still small in frame,
  # so an absolute threshold throws out real people. Bystanders come in around
  # 30% of the main face, real pairs at 85% or more.
  biggest=$("$T/faces" "$photo" | awk '/^face/ { if ($4 > m) m = $4 } END { print m+0 }')
  minface=$(python3 -c "print(int($biggest * 0.45))")

  n=0
  while read -r kw fx fy fw fh _rollkw roll _; do
    [ "$kw" = "face" ] || continue
    if [ "$fw" -lt "$minface" ]; then
      echo "    skipping a background face (${fw}px, under 45% of ${biggest}px)"
      continue
    fi
    n=$((n+1))
    if scripts/head-sticker.sh "$T/$slug-matte.png" "$fx" "$fy" "$fw" "$fh" \
         "$OUT/$slug-head-$n.webp" "$roll"; then
      echo "    head $n ok"
    else
      echo "    head $n failed, skipped"; n=$((n-1))
    fi
  done < <("$T/faces" "$photo")
  echo "$slug|$n" >> "$manifest"
done

# ---- generated manifest the app imports ----
{
  echo '// GENERATED by scripts/process-gallery.sh. Do not edit by hand.'
  echo '// Re-run the script after adding or removing photos.'
  echo ''
  echo 'export type GalleryPhoto = { slug: string; heads: number };'
  echo ''
  echo 'export const GALLERY: GalleryPhoto[] = ['
  while IFS='|' read -r slug heads; do
    printf '  { slug: "%s", heads: %s },\n' "$slug" "$heads"
  done < "$manifest"
  echo '];'
} > src/lib/gallery.ts

echo
printf '%-34s %8s  %s\n' FILE BYTES DIMS
for f in "$OUT"/*.webp; do
  printf '%-34s %8s  %s\n' "$(basename "$f")" "$(stat -f%z "$f")" "$(magick identify -format '%wx%h' "$f")"
done
total=$(find "$OUT" -name '*.webp' -exec stat -f%z {} + | awk '{s+=$1} END {print s+0}')
echo "TOTAL: $total bytes ($((total/1024)) KB)"
